### PR TITLE
Modularize edd

### PR DESCRIPTION
**Pull request by ipbabble**
I moved this to use the modules dir as mentioned by @abhatt-rh

### CODE REVIEW

**Comment by mbaldessari** [comment]
This is an automated message:

You can preview this docs PR at http://362.docs-pr.validatedpatterns.io
Note that they get generated every five minutes, so please wait a bit.

**Comment by ipbabble** [comment]
I'm not sure why the htmltest is failing. @abhatt-rh  (?) I did rename the getting-started but I think I was complete.

**Comment by ipbabble** [comment]
I think I see an issue.

**Comment by ipbabble** [comment]
Can some take a look at this. The links look fine.

**Comment by abhatt-rh** [comment]
> I'm not sure why the htmltest is failing. @abhatt-rh (?) I did rename the getting-started but I think I was complete.

I see the same issue with Html tests failing to recognize the renamed files on one of my own PRs. See [here](https://github.com/validatedpatterns/docs/actions/runs/6472388870/job/17957292758?pr=310). Not sure if that's the sole issue but that something I see is common between our failed results

**Pull request merged**
