### PR TITLE
Align htmltest versions with homepage-container

### PR DESCRIPTION
**Pull request by leifmadsen**
Align the htmltest versions with what is found in the homepage-container, with the hope that this will resolve the test issues once and for all.

### CODE REVIEW

**Comment by mbaldessari** [comment]
This is an automated message:

You can preview this docs PR at http://461.docs-pr.validatedpatterns.io
Note that they get generated every five minutes, so please wait a bit.

**Comment by leifmadsen** [comment]
Huzzuh!

**Comment by mbaldessari** [comment]
Ha! Excellent catch @leifmadsen , thanks!!

**Pull request merged**
