### PR TITLE
RegionalDR VP docs

### PR DESCRIPTION
**Pull request by r2dedios**
Including docs and diagrams for the RegionalDR VP

### CODE REVIEW

**Comment by TomerFi** [comment]
> This is an automated message:
> 
> You can preview this docs PR at http://481.docs-pr.validatedpatterns.io Note that they get generated every five minutes, so please wait a bit.

@mbaldessari @r2dedios 
I'm sorry, but I haven't found time to review this yet. I want to start today. Do you think we can still use the preview site?

**Comment by r2dedios** [comment]
@mbaldessari Ready to review.

The "HTMLTest" actions is failing due to a redirect loop on "blog/2024-01-16-deploying-mcg-with-cisco-flashstack-portworx/index.html" Should we ignore it?

**Comment by mbaldessari** [comment]
> @mbaldessari Ready to review.
> 
> The "HTMLTest" actions is failing due to a redirect loop on "blog/2024-01-16-deploying-mcg-with-cisco-flashstack-portworx/index.html" Should we ignore it?

Yeah that was just a temporary fluke. You do need to drop the `aliases: /agof/` though, that is wrong

**Comment by r2dedios** [comment]
Hi @mbaldessari I dropped the alias as you said, but still failing.. I'm not sure If I need to modify something else.

Thanks

**Comment by r2dedios** [comment]
@mbaldessari ?

**Comment by TomerFi** [comment]
Thank you guys!

**Pull request merged**
