### PR TITLE
Adding links to see page history and report doc bugs

### PR DESCRIPTION
**Pull request by danmacpherson**

### CODE REVIEW

**Comment by mbaldessari** [comment]
This is an automated message:

You can preview this docs PR at http://363.docs-pr.validatedpatterns.io
Note that they get generated every five minutes, so please wait a bit.

**Comment by danmacpherson** [comment]
Hey @abhatt-rh, I still need to merge this but wanted to check with you if there was anything else we need to do here?

**Comment by abhatt-rh** [comment]
> Hey @abhatt-rh, I still need to merge this but wanted to check with you if there was anything else we need to do here?

@danmacpherson LGTM! :+1:

**Comment by abhatt-rh** [comment]
@danmacpherson Thank you for getting this merged! :raised_hands:
This is going to be so helpful :tada:

**Pull request merged**
