### PR TITLE
feat: Coco pattern documentation

### PR DESCRIPTION
**Pull request by butler54**
**Currently a WIP**

Documentation for the MVP CoCo pattern. 

Signed-off-by: Chris Butler <chris.butler@redhat.com>

### CODE REVIEW

**Comment by mbaldessari** [comment]
This is an automated message:

You can preview this docs PR at http://482.docs-pr.validatedpatterns.io
Note that they get generated every five minutes, so please wait a bit.

**Comment by butler54** [comment]
@mbaldessari not sure what the deal is there. With the exception of the localhost URL (which is in a code block and I would not expect to be picked up) those URLs *will* exist onc ethe PR is merged.

**Comment by mbaldessari** [comment]
> @mbaldessari not sure what the deal is there. With the exception of the localhost URL (which is in a code block and I would not expect to be picked up) those URLs _will_ exist onc ethe PR is merged.

Yeah sometimes htmltest is a bit on crack. Can you just try and rebase this branch against latest main? We landed a few fixes in the htmltest CI (they might or might not help not sure)

**Comment by beekhof** [comment]
stupid html test

**Pull request merged**
