### PR TITLE
Add link to patterns workshop

### PR DESCRIPTION
**Pull request by day0hero**

### CODE REVIEW

**Comment by mbaldessari** [comment]
This is an automated message:

You can preview this docs PR at http://459.docs-pr.validatedpatterns.io
Note that they get generated every five minutes, so please wait a bit.

**Comment by leifmadsen** [comment]
I've created a PR against the base branch (https://github.com/day0hero/docs/pull/1) because this change looks funny on the title bar.

I think the changes should actually go into a `layouts/partials/menu-workshop.html` probably but I'm not sure if that's entirely necessary.

**Comment by leifmadsen** [comment]
@day0hero also if you rebase this against `main` it should also result in HtmlTest passing as I recently updated everything to get it working.

**Comment by danmacpherson** [comment]
Closing this in favor of #463

**Pull request closed without merging**
