### PR TITLE
Fix multiple docs and testing problems

### PR DESCRIPTION
**Pull request by leifmadsen**
Fix various problems within the documentation build.

* All WARNs have now been fixed by updating the header positions within
  the documentation to avoid assemblies having zero-level titles.
* Fix up paths to some images which were broken by using a relative path
  (there may be more to fix).
* Fix the name of the Testing Artefacts learning module to be named
  Testing Artifacts (along with reference links).
* Fix the htmltest job.

Signed-off-by: Leif Madsen <lmadsen@redhat.com>

### CODE REVIEW

**Comment by mbaldessari** [comment]
This is an automated message:

You can preview this docs PR at http://460.docs-pr.validatedpatterns.io
Note that they get generated every five minutes, so please wait a bit.

**Comment by leifmadsen** [comment]
Looks like I missed one hash update. Will fix tonight when I get home.

**Comment by leifmadsen** [comment]
Huh not sure what is going on with the github action, because I can't reproduce this locally. Running `make htmltest` passes fine locally, and I don't actually have that hash in the local `public/learn/index.html`. I wonder if there is some sort of caching going on here...?

**Comment by mbaldessari** [comment]
It seems to me that htmltest is just drunk: 
```
$ make build && grep _prereq public/learn/index.html
podman run -it --security-opt label=disable --pull=newer --net=host -v /home/michele/Engineering/cloud-patterns/docs:/site:"rw,z" --entrypoint hugo quay.io/hybridcloudpatterns/homepage-container:latest
Start building sites …
hugo v0.133.1-47d00202e7e61769ce4d14691e43b27852c9cce4+extended linux/amd64 BuildDate=2024-08-26T13:58:46Z VendorInfo=gohugoio


                   | EN
-------------------+------
  Pages            | 318
  Paginator pages  |  18
  Non-page files   |   0
  Static files     | 586
  Processed images |   0
  Aliases          | 208
  Cleaned          |   0

Total in 17471 ms
```

I am merging this because it is a vast improvement to the current status quo. *Thanks* a bunch, Leif!

**Pull request merged**
