### PR TITLE
Contribute review 1

### PR DESCRIPTION
**Pull request by ipbabble**
A random review of some of the wording resulted in some cleaner language and additions.

### CODE REVIEW

**Comment by ipbabble** [comment]
@mbaldessari this and other PRs seem to be heal up on some html links stuff.  Can we take a look and see if we can fix the tests?

**Comment by ipbabble** [comment]
@abhatt-rh  can you check the tests too?

**Comment by abhatt-rh** [comment]
@ipbabble I fixed a bunch of `htmltest` related errors in #275

**Comment by ipbabble** [comment]
> @ipbabble I fixed a bunch of `htmltest` related errors in #275

I reran the tests and they failed @abhatt-rh

**Comment by abhatt-rh** [comment]
> > @ipbabble I fixed a bunch of `htmltest` related errors in #275
> 
> I reran the tests and they failed @abhatt-rh
Is it correct to assume that you have fetched the latest changes, rebased the PR and then re-running the tests?

**Comment by mbaldessari** [comment]
I rebased it and am merging it

**Pull request merged**
