### PR TITLE
Create blogs

### PR DESCRIPTION
**Pull request by mdstjean**
images for blog posts

### CODE REVIEW

**Comment by mbaldessari** [comment]
This is an automated message:

You can preview this docs PR at http://416.docs-pr.validatedpatterns.io
Note that they get generated every five minutes, so please wait a bit.

**Comment by mdstjean** [comment]
creating a folder to put images used for blog posts

**Comment by mbaldessari** [comment]
@mdstjean Do you know where this is needed? Or is it more of a future need?

**Comment by mdstjean** [comment]
> @mdstjean Do you know where this is needed? Or is it more of a future need?

If I remember correctly, I was trying to put some images into some of the blog posts (either Lester's on Cisco, or Jonny's on Intel), and so I was trying to create a folder where we could drop images to be used in the blog posts. This was back in March, so I think I just let it go... but it would be a nice-to-have

**Comment by mbaldessari** [comment]
ack, let's add this folder once we actually do use/need that, so we don't have an empty folder until then

**Pull request closed without merging**
