### PR TITLE
Installing the tooling dependencies is already in Prerequisites.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by mbaldessari** [comment]
You can preview this docs PR at http://338.docs-pr.validatedpatterns.io
Note that they get generated every five minutes, so please wait a bit.

**Comment by adelton** [comment]
Thanks for that pointer. At http://338.docs-pr.validatedpatterns.io/patterns/multicloud-gitops/mcg-getting-started/ I see the change applied. What are the next steps?

**Comment by mbaldessari** [comment]
Thanks! :)

**Pull request merged**
